### ISSUE TITLE
[IDEA] Log how many viewers in total going to a host!

### ISSUE THREAD

**Issue by CreativeCodeCat** [zoton2/Twitch-Team-Hosting-Bot#7]
Title says it all man <3 awesome bot so far <3

Also a backlist of streamers not to host would be nice too and to fix the manualChannelList to add to the teams so it host both not only the manualChannelList when there is some

**Comment by zoton2** [comment]
Didn't know anyone was actively using the bot. Heh. If you are, do you mind telling me where? Would be nice seeing it in action and maybe add where it's being used to the README.

The viewers for the host could be done in the code [around here](https://github.com/zoton2/Twitch-Team-Hosting-Bot/blob/master/lib/hosting.js#L252) because it reports the view count. How do you think this should be logged? Just in the normal logs or to a separate file too? If so, how.

A blacklist could be done easily.

Right now the manual channel list is for channels to host on, not of channels to host. Is this what you thought? From what you've said it sounds like you want it to try and host channels from the team and also a list of extra channels too. Am I understanding you correctly?

**Comment by CreativeCodeCat** [comment]
yes this is correct and we are doing it for TeamNoSleep :) on twitch :P would be awesome to work with you on this and get new features as we work and we where wanting it to log into the Teamname.log file under the area listed below

 [2016-06-04 22:33:59] Average viewers on those channels: 14.
[2016-06-04 22:33:59] Total viewers on those channels: 119.

PS Feel free join my discord if you want to talk to me about it! http://discord.me/lawlypopzz

**Comment by zoton2** [comment]
Had a discussion with @LawlyPopz and have technically implemented the main idea in this issue, so going to leave this closed.
